//
//  DictionaryDocument.swift
//  SwiftAutoEdit
//
//

import Cocoa
import OSAKit


class DictionaryDocument: NSDocument {
    
    @IBOutlet var dictionaryController: OSADictionaryController!
    
    var sdef: Data?

    override var windowNibName: String? {
        return "DictionaryDocument"
    }
    
    override func windowControllerDidLoadNib(_ windowController: NSWindowController) {
        // TO DO: would help to have SA's SDEF generator insert a [non-standard] `format="SwiftAutomation"` in top-level element; if not found, assume the SDEF is in original AS format and call installed/embedded aeglue to translate the SDEF to SA format using default autogenerated prefix
        if let sdef = self.sdef, let dict = OSADictionary(data: sdef, error: nil) {
            self.dictionaryController.setDictionary(dict)
        } else {
            NSLog("Can't display SDEF.")
        }
    }
    
    override func read(from data: Data, ofType typeName: String) throws {
        self.sdef = data
    }
}

